### ISSUE TITLE
[Chore] Replace the deprecated Redux implementation with Redux Toolkit

### ISSUE THREAD

**Issue by olivierobert** [nghiavt2906/Web-Scraping-FE#7]
## Issue

The current Redux implementation is now deprecated. Redux Toolkit is now the recommended approach for writing Redux logic: https://redux.js.org/introduction/why-rtk-is-redux-today

![image](https://user-images.githubusercontent.com/696529/223946319-c12809aa-6757-4574-9ca1-e8cc1329bc31.png)

At the minimum, the official guides recommend replacing `createStore` with `configureStore` as the dev-mode middleware will also help catch accidental mutation and serializability errors in existing code bases. VS Code even shows a deprecated warning: 

![image](https://user-images.githubusercontent.com/696529/223946692-0aa0ea2e-883d-494a-ab10-4b1171ff1ea6.png)

**Comment by nghiavt2906** [comment]
I have done adding Redux Toolkit. Please have a look

**Comment by olivierobert** [comment]
That was fast 😁 As a future improvement, you could look into using [slices](https://redux-toolkit.js.org/api/createslice).
